name: imei_validator
version: 0.1.0
author: Jonathan White <thinkdigitalrepair@gmail.com
description: A library for checking cell phone IMEIs with the Luhn algorithm.
homepage: https://github.com/thinkdigitalrepair/imei_validator
dev_dependencies:
  unittest: ">0.10.1 <0.11.0"
environment:
  sdk: '>=0.8.7 <2.0.0'