name: imei_validator
version: 0.1.2
author: Jonathan White <thinkdigitalrepair@gmail.com>
description: A library for checking cell phone IMEIs with the Luhn algorithm.
homepage: https://github.com/thinkdigitalrepair/imei_validator
dev_dependencies:
  unittest: ">0.10.1 <0.11.0"
environment:
  sdk: '>=1.8.3 <3.0.0'